services:
  # Connect using:
  # export ELASTICSEARCH_URL=http://localhost:9200
  # export ELASTICSEARCH_USERNAME=elastic
  # export ELASTICSEARCH_PASSWORD=password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch-node
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-password}"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elasticsearch-net

volumes:
  elasticsearch-data:

networks:
  elasticsearch-net:
    driver: bridge