name: OpenSearch Staging Catchup

on:
  workflow_dispatch:
    inputs:
      index_name:
        description: 'Index name to catchup'
        required: true
        type: string

jobs:
  catchup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      
      - name: Run catchup
        run: |
          rake opensearch:catchup[${{ github.event.inputs.index_name }}]
        env:
          OPENSEARCH_URL: ${{ secrets.OPENSEARCH_STAGING_URL }}
          SCHEMAS_PATH: schemas